apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-python
        tier: hello-python
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-python:$BUILD_TAG
        name: hello-python
        ports:
        - containerPort: 80
          name: hello-python
