apiVersion: v1
kind: Service
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-python
    tier: hello-python
  type: NodePort 
