apiVersion: v1
kind: Service
metadata:
  name: flask-alpine
  labels:
    app: flask-alpine
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-alpine
    tier: flask-alpine
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-alpine
  labels:
    app: flask-alpine
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-alpine
        tier: flask-alpine
    spec:
      containers:
      - image: 127.0.0.1:30400/flask-alpine:version
        name: flask-alpine
        ports:
        - containerPort: 80
          name: flask-alpine
