apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default
automountServiceAccountToken: true
--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-alpine
  labels:
    app: flask-alpine
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flask-alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-alpine
        tier: flask-alpine
    spec:
      containers:
      - image: 127.0.0.1:30400/flask-alpine:version
        name: flask-alpine
        ports:
        - containerPort: 80
          name: flask-alpine
