apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://130.211.96.23
  name: gke_ci-cd-pipeline-255118_europe-west1-c_ci-cd-cluster
contexts:
- context:
    cluster: ""
    namespace: default
    user: ""
  name: default
- context:
    cluster: gke_ci-cd-pipeline-255118_europe-west1-c_ci-cd-cluster
    user: gke_ci-cd-pipeline-255118_europe-west1-c_ci-cd-cluster
  name: gke_ci-cd-pipeline-255118_europe-west1-c_ci-cd-cluster
current-context: gke_ci-cd-pipeline-255118_europe-west1-c_ci-cd-cluster
kind: Config
preferences: {}
users:
- name: gke_ci-cd-pipeline-255118_europe-west1-c_ci-cd-cluster
  user:
    auth-provider:
      config:
        access-token: ya29.Iq8BmwetOPG9ryjvXkBu3AOAY__O9CC54CODQeA_D7LdDYKmJoop6ziCN2KqFP1HLeWF2Icmaxc-_NIo5u6eEPhIU-QvKIzwTDfaPtRcCEuf3Bbr714EOI-kFI2iW5c6iDG3ig6y-NDUtVZJvowjc45ToRVOM8iSWKs8Q43l-bvrNH3VHAsTRWn3ilJIyPcpOPAM3dRD9ASiz23X0tEUjU5jc5y8AALlhoEOVA4cKpiE1w
        cmd-args: config config-helper --format=json
        cmd-path: /google/google-cloud-sdk/bin/gcloud
        expiry: "2019-10-09T20:49:09Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
