apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kubectl-jenkins-context
data:
  kubectl-config-context.sh: |-
    #!/bin/bash -v
    kubectl config set-credentials jenkins --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    kubectl config set-cluster minikube --server="https://192.168.99.104:8443" --certificate-authority="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    kubectl config set-context jenkins-minikube --cluster=minikube --user=jenkins --namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    kubectl config use-context jenkins-minikube
    chmod 755 ~/.kube/config
    
--
apiVersion: v1
kind: Service
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-python
    tier: hello-python
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  strategy:
    type: Create
  template:
    metadata:
      labels:
        app: hello-python
        tier: hello-python
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-python:$BUILD_TAG
        name: hello-python
        ports:
        - containerPort: 80
          name: hello-python
